TOPDIR = ..

!include $(TOPDIR)/defines.mak

OBJECTS = ntmap.$(OBJ) scanline.$(OBJ)


!ifdef OGL

NO_ASM = 1

!else

OBJECTS = $(OBJECTS) tmapflat.$(OBJ)

!ifndef NO_ASM
OBJECTS = $(OBJECTS) \
 ntmap.$(OBJ) tmapflat.$(OBJ) \
 tmap_ll.$(OBJ) tmap_flt.$(OBJ) tmapfade.$(OBJ) tmap_lin.$(OBJ) \
 tmapppro.$(OBJ) tmappent.$(OBJ) tmap_per.$(OBJ)
!endif

!endif

OUTPUT = $(LIBDIR)texmap.$(ARC)

!include $(TOPDIR)/default.nt
